---
port: 9997
api: http://github.my-card.in/servers.json
xmpp:
  jid: zh99998@gmail.com/mycard-server
  password: 
  host: talk.google.com
  conference: mycard@conference.jabber.org/mycard
servers:
- auth: true
  id: 2
  index: http://122.0.65.70:7922/
  ip: 122.0.65.70
  login: http://master.smdcn.net:7922/?operation=passcheck&username={name}&pass={password}
  max_rooms: 200
  name: mycard
  port: 7911
  register: http://master.smdcn.net:7922/?pass={key}&operation=forceuserpass&username={name}&password={password}
  rooms: []